// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AdminAtData, AdminAtErrors, AdminAtResetData, AdminAtResetErrors, AdminAtResetResponses, AdminAtResponses, AdminCapabilitiesData, AdminCapabilitiesErrors, AdminCapabilitiesResponses, AdminQueueData, AdminQueueErrors, AdminQueueResponses, AdminReconcileData, AdminReconcileErrors, AdminReconcileResponses, AdminVacuumData, AdminVacuumErrors, AdminVacuumResponses, CallForwardingGetData, CallForwardingGetErrors, CallForwardingGetResponses, CallForwardingUpdateData, CallForwardingUpdateErrors, CallForwardingUpdateResponses, CallsAnswerData, CallsAnswerErrors, CallsAnswerResponses, CallsDialData, CallsDialErrors, CallsDialResponses, CallsDtmfData, CallsDtmfErrors, CallsDtmfResponses, CallsGetData, CallsGetErrors, CallsGetResponses, CallsHangupData, CallsHangupErrors, CallsHangupResponses, CallsHoldData, CallsHoldErrors, CallsHoldResponses, CallsListData, CallsListErrors, CallsListResponses, CallsMergeData, CallsMergeErrors, CallsMergeResponses, CallsRejectData, CallsRejectErrors, CallsRejectResponses, CallsResumeData, CallsResumeErrors, CallsResumeResponses, EventsListData, EventsListErrors, EventsListResponses, SmsDeleteData, SmsDeleteErrors, SmsDeleteResponses, SmsGetData, SmsGetErrors, SmsGetResponses, SmsListData, SmsListErrors, SmsListResponses, SmsSendData, SmsSendErrors, SmsSendResponses, StatusGetData, StatusGetErrors, StatusGetResponses, VoicemailsAudioData, VoicemailsAudioResponses, VoicemailsDeleteData, VoicemailsDeleteErrors, VoicemailsDeleteResponses, VoicemailsGetData, VoicemailsGetErrors, VoicemailsGetResponses, VoicemailsListData, VoicemailsListErrors, VoicemailsListResponses, VoicemailsSyncData, VoicemailsSyncErrors, VoicemailsSyncResponses, VoicemailsUpdateData, VoicemailsUpdateErrors, VoicemailsUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Send a raw AT command (flag-gated)
 */
export const adminAt = <ThrowOnError extends boolean = false>(options: Options<AdminAtData, ThrowOnError>): RequestResult<AdminAtResponses, AdminAtErrors, ThrowOnError> => (options.client ?? client).post<AdminAtResponses, AdminAtErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/admin/at',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * AT+CFUN=1,1 — reboot modem (flag-gated)
 */
export const adminAtReset = <ThrowOnError extends boolean = false>(options: Options<AdminAtResetData, ThrowOnError>): RequestResult<AdminAtResetResponses, AdminAtResetErrors, ThrowOnError> => (options.client ?? client).post<AdminAtResetResponses, AdminAtResetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/admin/at-reset',
    ...options
});

/**
 * List enabled admin capabilities
 */
export const adminCapabilities = <ThrowOnError extends boolean = false>(options: Options<AdminCapabilitiesData, ThrowOnError>): RequestResult<AdminCapabilitiesResponses, AdminCapabilitiesErrors, ThrowOnError> => (options.client ?? client).get<AdminCapabilitiesResponses, AdminCapabilitiesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/admin/capabilities',
    ...options
});

/**
 * Diagnostic info for atexec queue
 */
export const adminQueue = <ThrowOnError extends boolean = false>(options: Options<AdminQueueData, ThrowOnError>): RequestResult<AdminQueueResponses, AdminQueueErrors, ThrowOnError> => (options.client ?? client).get<AdminQueueResponses, AdminQueueErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/admin/queue',
    ...options
});

/**
 * Run reconciler synchronously
 */
export const adminReconcile = <ThrowOnError extends boolean = false>(options: Options<AdminReconcileData, ThrowOnError>): RequestResult<AdminReconcileResponses, AdminReconcileErrors, ThrowOnError> => (options.client ?? client).post<AdminReconcileResponses, AdminReconcileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/admin/reconcile',
    ...options
});

/**
 * Run SQLite VACUUM
 */
export const adminVacuum = <ThrowOnError extends boolean = false>(options: Options<AdminVacuumData, ThrowOnError>): RequestResult<AdminVacuumResponses, AdminVacuumErrors, ThrowOnError> => (options.client ?? client).post<AdminVacuumResponses, AdminVacuumErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/admin/vacuum',
    ...options
});

/**
 * Get voice call-forwarding status
 */
export const callForwardingGet = <ThrowOnError extends boolean = false>(options: Options<CallForwardingGetData, ThrowOnError>): RequestResult<CallForwardingGetResponses, CallForwardingGetErrors, ThrowOnError> => (options.client ?? client).get<CallForwardingGetResponses, CallForwardingGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/call-forwarding',
    ...options
});

/**
 * Update a voice call-forwarding rule
 */
export const callForwardingUpdate = <ThrowOnError extends boolean = false>(options: Options<CallForwardingUpdateData, ThrowOnError>): RequestResult<CallForwardingUpdateResponses, CallForwardingUpdateErrors, ThrowOnError> => (options.client ?? client).put<CallForwardingUpdateResponses, CallForwardingUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/call-forwarding/{reason}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List calls
 */
export const callsList = <ThrowOnError extends boolean = false>(options: Options<CallsListData, ThrowOnError>): RequestResult<CallsListResponses, CallsListErrors, ThrowOnError> => (options.client ?? client).get<CallsListResponses, CallsListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls',
    ...options
});

/**
 * Place an outbound call
 */
export const callsDial = <ThrowOnError extends boolean = false>(options: Options<CallsDialData, ThrowOnError>): RequestResult<CallsDialResponses, CallsDialErrors, ThrowOnError> => (options.client ?? client).post<CallsDialResponses, CallsDialErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a call by ID
 */
export const callsGet = <ThrowOnError extends boolean = false>(options: Options<CallsGetData, ThrowOnError>): RequestResult<CallsGetResponses, CallsGetErrors, ThrowOnError> => (options.client ?? client).get<CallsGetResponses, CallsGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}',
    ...options
});

/**
 * Answer a ringing call
 */
export const callsAnswer = <ThrowOnError extends boolean = false>(options: Options<CallsAnswerData, ThrowOnError>): RequestResult<CallsAnswerResponses, CallsAnswerErrors, ThrowOnError> => (options.client ?? client).post<CallsAnswerResponses, CallsAnswerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}/answer',
    ...options
});

/**
 * Send DTMF on an active call
 */
export const callsDtmf = <ThrowOnError extends boolean = false>(options: Options<CallsDtmfData, ThrowOnError>): RequestResult<CallsDtmfResponses, CallsDtmfErrors, ThrowOnError> => (options.client ?? client).post<CallsDtmfResponses, CallsDtmfErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}/dtmf',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Hang up an active call
 */
export const callsHangup = <ThrowOnError extends boolean = false>(options: Options<CallsHangupData, ThrowOnError>): RequestResult<CallsHangupResponses, CallsHangupErrors, ThrowOnError> => (options.client ?? client).post<CallsHangupResponses, CallsHangupErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}/hangup',
    ...options
});

/**
 * Place an active call on hold
 */
export const callsHold = <ThrowOnError extends boolean = false>(options: Options<CallsHoldData, ThrowOnError>): RequestResult<CallsHoldResponses, CallsHoldErrors, ThrowOnError> => (options.client ?? client).post<CallsHoldResponses, CallsHoldErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}/hold',
    ...options
});

/**
 * Merge an active and a held call
 */
export const callsMerge = <ThrowOnError extends boolean = false>(options: Options<CallsMergeData, ThrowOnError>): RequestResult<CallsMergeResponses, CallsMergeErrors, ThrowOnError> => (options.client ?? client).post<CallsMergeResponses, CallsMergeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}/merge',
    ...options
});

/**
 * Reject a ringing call
 */
export const callsReject = <ThrowOnError extends boolean = false>(options: Options<CallsRejectData, ThrowOnError>): RequestResult<CallsRejectResponses, CallsRejectErrors, ThrowOnError> => (options.client ?? client).post<CallsRejectResponses, CallsRejectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}/reject',
    ...options
});

/**
 * Resume a held call
 */
export const callsResume = <ThrowOnError extends boolean = false>(options: Options<CallsResumeData, ThrowOnError>): RequestResult<CallsResumeResponses, CallsResumeErrors, ThrowOnError> => (options.client ?? client).post<CallsResumeResponses, CallsResumeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/calls/{id}/resume',
    ...options
});

/**
 * List daemon events
 */
export const eventsList = <ThrowOnError extends boolean = false>(options: Options<EventsListData, ThrowOnError>): RequestResult<EventsListResponses, EventsListErrors, ThrowOnError> => (options.client ?? client).get<EventsListResponses, EventsListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/events',
    ...options
});

/**
 * List SMS messages
 */
export const smsList = <ThrowOnError extends boolean = false>(options: Options<SmsListData, ThrowOnError>): RequestResult<SmsListResponses, SmsListErrors, ThrowOnError> => (options.client ?? client).get<SmsListResponses, SmsListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sms',
    ...options
});

/**
 * Send an SMS
 */
export const smsSend = <ThrowOnError extends boolean = false>(options: Options<SmsSendData, ThrowOnError>): RequestResult<SmsSendResponses, SmsSendErrors, ThrowOnError> => (options.client ?? client).post<SmsSendResponses, SmsSendErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete an SMS from history
 */
export const smsDelete = <ThrowOnError extends boolean = false>(options: Options<SmsDeleteData, ThrowOnError>): RequestResult<SmsDeleteResponses, SmsDeleteErrors, ThrowOnError> => (options.client ?? client).delete<SmsDeleteResponses, SmsDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sms/{id}',
    ...options
});

/**
 * Get a single SMS by ID
 */
export const smsGet = <ThrowOnError extends boolean = false>(options: Options<SmsGetData, ThrowOnError>): RequestResult<SmsGetResponses, SmsGetErrors, ThrowOnError> => (options.client ?? client).get<SmsGetResponses, SmsGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/sms/{id}',
    ...options
});

/**
 * Get modem status
 */
export const statusGet = <ThrowOnError extends boolean = false>(options: Options<StatusGetData, ThrowOnError>): RequestResult<StatusGetResponses, StatusGetErrors, ThrowOnError> => (options.client ?? client).get<StatusGetResponses, StatusGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/status',
    ...options
});

/**
 * List voicemail
 */
export const voicemailsList = <ThrowOnError extends boolean = false>(options: Options<VoicemailsListData, ThrowOnError>): RequestResult<VoicemailsListResponses, VoicemailsListErrors, ThrowOnError> => (options.client ?? client).get<VoicemailsListResponses, VoicemailsListErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/voicemails',
    ...options
});

/**
 * Sync voicemail mailbox
 */
export const voicemailsSync = <ThrowOnError extends boolean = false>(options: Options<VoicemailsSyncData, ThrowOnError>): RequestResult<VoicemailsSyncResponses, VoicemailsSyncErrors, ThrowOnError> => (options.client ?? client).post<VoicemailsSyncResponses, VoicemailsSyncErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/voicemails/sync',
    ...options
});

/**
 * Delete voicemail
 */
export const voicemailsDelete = <ThrowOnError extends boolean = false>(options: Options<VoicemailsDeleteData, ThrowOnError>): RequestResult<VoicemailsDeleteResponses, VoicemailsDeleteErrors, ThrowOnError> => (options.client ?? client).delete<VoicemailsDeleteResponses, VoicemailsDeleteErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/voicemails/{id}',
    ...options
});

/**
 * Get voicemail metadata
 */
export const voicemailsGet = <ThrowOnError extends boolean = false>(options: Options<VoicemailsGetData, ThrowOnError>): RequestResult<VoicemailsGetResponses, VoicemailsGetErrors, ThrowOnError> => (options.client ?? client).get<VoicemailsGetResponses, VoicemailsGetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/voicemails/{id}',
    ...options
});

/**
 * Update voicemail read state
 */
export const voicemailsUpdate = <ThrowOnError extends boolean = false>(options: Options<VoicemailsUpdateData, ThrowOnError>): RequestResult<VoicemailsUpdateResponses, VoicemailsUpdateErrors, ThrowOnError> => (options.client ?? client).put<VoicemailsUpdateResponses, VoicemailsUpdateErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/voicemails/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Play or download voicemail audio
 */
export const voicemailsAudio = <ThrowOnError extends boolean = false>(options: Options<VoicemailsAudioData, ThrowOnError>): RequestResult<VoicemailsAudioResponses, unknown, ThrowOnError> => (options.client ?? client).get<VoicemailsAudioResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/voicemails/{id}/audio',
    ...options
});
