// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AdminAtInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Raw AT command
     */
    cmd: string;
    /**
     * Per-command timeout
     */
    timeout_ms?: number;
};

export type AdminAtOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    code: number;
    final: string;
    lines: Array<string> | null;
};

export type AdminCapabilitiesOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    at_passthrough: boolean;
    modem_reset: boolean;
};

export type ApiError = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    error: ApiErrorWrappedStruct;
};

export type ApiErrorWrappedStruct = {
    code: string;
    details?: unknown;
    message: string;
};

export type CallForwardingGetOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<CallForwardingRuleJson> | null;
};

export type CallForwardingRuleJson = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * True when the network confirmed the current state
     */
    available: boolean;
    enabled: boolean;
    /**
     * Carrier or modem status error when current state is unavailable
     */
    error?: string;
    number?: string;
    reason: 'unconditional' | 'busy' | 'no_reply' | 'unreachable';
    /**
     * Ring time before forwarding; only used for no_reply
     */
    timeout_seconds?: number;
};

export type CallForwardingUpdateInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    enabled: boolean;
    number?: string;
    timeout_seconds?: number;
};

export type CallJson = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    answered_at?: string;
    direction: 'in' | 'out';
    duration_ms?: number;
    end_reason?: string;
    ended_at?: string;
    from?: string;
    id: string;
    started_at: string;
    state: 'ringing' | 'dialing' | 'alerting' | 'active' | 'held' | 'ended' | 'missed' | 'rejected';
    to?: string;
};

export type CallsDtmfInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * DTMF digits ([0-9A-D*#]+)
     */
    digits: string;
    /**
     * Per-digit duration in ms
     */
    duration_ms?: number;
};

export type CallsDialInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    to: string;
};

export type CallsListOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<CallJson> | null;
};

export type EventJson = {
    detail?: string;
    id: number;
    kind: string;
    raw?: string;
    ref_id?: string;
    ref_kind?: string;
    ts: string;
};

export type EventsListOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<EventJson> | null;
};

export type OutboundSmsResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    body: string;
    direction: 'out';
    encoding: 'gsm7' | 'ucs2' | '8bit';
    error_code?: string;
    error_detail?: string;
    id: string;
    parts: Array<SendSmsPart> | null;
    state: 'queued' | 'submitted' | 'accepted' | 'delivered' | 'failed' | 'indeterminate';
    to: string;
    ts: string;
};

export type SendSmsPart = {
    mr: number;
};

export type SmsListBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Either inbound or outbound items depending on the direction query parameter
     */
    items: Array<unknown> | null;
};

export type SmsSendInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Message text
     */
    body: string;
    /**
     * Request delivery report from carrier
     */
    delivery_report?: boolean;
    /**
     * E.164 number or short code if raw=1
     */
    to: string;
};

export type StatusBattery = {
    voltage_v: number;
};

export type StatusModem = {
    epoch: number;
    firmware: string;
    imei: string;
    model: string;
};

export type StatusNetwork = {
    band: string;
    csq: number;
    registered: boolean;
    rsrp_dbm: number;
    rsrq_db: number;
    tech: 'LTE' | 'UMTS' | 'GSM' | 'none';
};

export type StatusResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    battery: StatusBattery;
    modem: StatusModem;
    network: StatusNetwork;
    sim: StatusSim;
    ts: string;
    uptime_s: number;
};

export type StatusSim = {
    iccid: string;
    imsi: string;
    operator: string;
    state: 'ready' | 'pin_required' | 'absent';
};

export type SyncResult = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    added: number;
    fetched: number;
    skipped: number;
    updated: number;
};

export type VoicemailListOutputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    items: Array<VoicemailResponse> | null;
};

export type VoicemailResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    audio_bytes: number;
    audio_url: string;
    content_type: string;
    duration_ms: number;
    from: string;
    id: string;
    read: boolean;
    read_at?: string;
    received_at: string;
    source_id: string;
    source_sms_id?: string;
    transcript?: string;
};

export type VoicemailUpdateInputBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Mark the voicemail heard or unheard
     */
    read: boolean;
};

export type AdminAtInputBodyWritable = {
    /**
     * Raw AT command
     */
    cmd: string;
    /**
     * Per-command timeout
     */
    timeout_ms?: number;
};

export type AdminAtOutputBodyWritable = {
    code: number;
    final: string;
    lines: Array<string> | null;
};

export type AdminCapabilitiesOutputBodyWritable = {
    at_passthrough: boolean;
    modem_reset: boolean;
};

export type ApiErrorWritable = {
    error: ApiErrorWrappedStruct;
};

export type CallForwardingGetOutputBodyWritable = {
    items: Array<CallForwardingRuleJsonWritable> | null;
};

export type CallForwardingRuleJsonWritable = {
    /**
     * True when the network confirmed the current state
     */
    available: boolean;
    enabled: boolean;
    /**
     * Carrier or modem status error when current state is unavailable
     */
    error?: string;
    number?: string;
    reason: 'unconditional' | 'busy' | 'no_reply' | 'unreachable';
    /**
     * Ring time before forwarding; only used for no_reply
     */
    timeout_seconds?: number;
};

export type CallForwardingUpdateInputBodyWritable = {
    enabled: boolean;
    number?: string;
    timeout_seconds?: number;
};

export type CallJsonWritable = {
    answered_at?: string;
    direction: 'in' | 'out';
    duration_ms?: number;
    end_reason?: string;
    ended_at?: string;
    from?: string;
    id: string;
    started_at: string;
    state: 'ringing' | 'dialing' | 'alerting' | 'active' | 'held' | 'ended' | 'missed' | 'rejected';
    to?: string;
};

export type CallsDtmfInputBodyWritable = {
    /**
     * DTMF digits ([0-9A-D*#]+)
     */
    digits: string;
    /**
     * Per-digit duration in ms
     */
    duration_ms?: number;
};

export type CallsDialInputBodyWritable = {
    to: string;
};

export type CallsListOutputBodyWritable = {
    items: Array<CallJsonWritable> | null;
};

export type EventsListOutputBodyWritable = {
    items: Array<EventJson> | null;
};

export type OutboundSmsResponseWritable = {
    body: string;
    direction: 'out';
    encoding: 'gsm7' | 'ucs2' | '8bit';
    error_code?: string;
    error_detail?: string;
    id: string;
    parts: Array<SendSmsPart> | null;
    state: 'queued' | 'submitted' | 'accepted' | 'delivered' | 'failed' | 'indeterminate';
    to: string;
    ts: string;
};

export type SmsListBodyWritable = {
    /**
     * Either inbound or outbound items depending on the direction query parameter
     */
    items: Array<unknown> | null;
};

export type SmsSendInputBodyWritable = {
    /**
     * Message text
     */
    body: string;
    /**
     * Request delivery report from carrier
     */
    delivery_report?: boolean;
    /**
     * E.164 number or short code if raw=1
     */
    to: string;
};

export type StatusResponseBodyWritable = {
    battery: StatusBattery;
    modem: StatusModem;
    network: StatusNetwork;
    sim: StatusSim;
    ts: string;
    uptime_s: number;
};

export type SyncResultWritable = {
    added: number;
    fetched: number;
    skipped: number;
    updated: number;
};

export type VoicemailListOutputBodyWritable = {
    items: Array<VoicemailResponseWritable> | null;
};

export type VoicemailResponseWritable = {
    audio_bytes: number;
    audio_url: string;
    content_type: string;
    duration_ms: number;
    from: string;
    id: string;
    read: boolean;
    read_at?: string;
    received_at: string;
    source_id: string;
    source_sms_id?: string;
    transcript?: string;
};

export type VoicemailUpdateInputBodyWritable = {
    /**
     * Mark the voicemail heard or unheard
     */
    read: boolean;
};

export type AdminAtData = {
    body: AdminAtInputBodyWritable;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/admin/at';
};

export type AdminAtErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type AdminAtError = AdminAtErrors[keyof AdminAtErrors];

export type AdminAtResponses = {
    /**
     * OK
     */
    200: AdminAtOutputBody;
};

export type AdminAtResponse = AdminAtResponses[keyof AdminAtResponses];

export type AdminAtResetData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/admin/at-reset';
};

export type AdminAtResetErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type AdminAtResetError = AdminAtResetErrors[keyof AdminAtResetErrors];

export type AdminAtResetResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AdminAtResetResponse = AdminAtResetResponses[keyof AdminAtResetResponses];

export type AdminCapabilitiesData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/admin/capabilities';
};

export type AdminCapabilitiesErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type AdminCapabilitiesError = AdminCapabilitiesErrors[keyof AdminCapabilitiesErrors];

export type AdminCapabilitiesResponses = {
    /**
     * OK
     */
    200: AdminCapabilitiesOutputBody;
};

export type AdminCapabilitiesResponse = AdminCapabilitiesResponses[keyof AdminCapabilitiesResponses];

export type AdminQueueData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/admin/queue';
};

export type AdminQueueErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type AdminQueueError = AdminQueueErrors[keyof AdminQueueErrors];

export type AdminQueueResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type AdminQueueResponse = AdminQueueResponses[keyof AdminQueueResponses];

export type AdminReconcileData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/admin/reconcile';
};

export type AdminReconcileErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type AdminReconcileError = AdminReconcileErrors[keyof AdminReconcileErrors];

export type AdminReconcileResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AdminReconcileResponse = AdminReconcileResponses[keyof AdminReconcileResponses];

export type AdminVacuumData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/admin/vacuum';
};

export type AdminVacuumErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type AdminVacuumError = AdminVacuumErrors[keyof AdminVacuumErrors];

export type AdminVacuumResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AdminVacuumResponse = AdminVacuumResponses[keyof AdminVacuumResponses];

export type CallForwardingGetData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/call-forwarding';
};

export type CallForwardingGetErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallForwardingGetError = CallForwardingGetErrors[keyof CallForwardingGetErrors];

export type CallForwardingGetResponses = {
    /**
     * OK
     */
    200: CallForwardingGetOutputBody;
};

export type CallForwardingGetResponse = CallForwardingGetResponses[keyof CallForwardingGetResponses];

export type CallForwardingUpdateData = {
    body: CallForwardingUpdateInputBodyWritable;
    headers: {
        Authorization: string;
    };
    path: {
        reason: 'unconditional' | 'busy' | 'no_reply' | 'unreachable';
    };
    query?: never;
    url: '/v1/call-forwarding/{reason}';
};

export type CallForwardingUpdateErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallForwardingUpdateError = CallForwardingUpdateErrors[keyof CallForwardingUpdateErrors];

export type CallForwardingUpdateResponses = {
    /**
     * OK
     */
    200: CallForwardingRuleJson;
};

export type CallForwardingUpdateResponse = CallForwardingUpdateResponses[keyof CallForwardingUpdateResponses];

export type CallsListData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: {
        since?: string;
        limit?: number;
    };
    url: '/v1/calls';
};

export type CallsListErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsListError = CallsListErrors[keyof CallsListErrors];

export type CallsListResponses = {
    /**
     * OK
     */
    200: CallsListOutputBody;
};

export type CallsListResponse = CallsListResponses[keyof CallsListResponses];

export type CallsDialData = {
    body: CallsDialInputBodyWritable;
    headers: {
        Authorization: string;
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: {
        raw?: boolean;
    };
    url: '/v1/calls';
};

export type CallsDialErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsDialError = CallsDialErrors[keyof CallsDialErrors];

export type CallsDialResponses = {
    /**
     * Created
     */
    201: CallJson;
};

export type CallsDialResponse = CallsDialResponses[keyof CallsDialResponses];

export type CallsGetData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}';
};

export type CallsGetErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsGetError = CallsGetErrors[keyof CallsGetErrors];

export type CallsGetResponses = {
    /**
     * OK
     */
    200: CallJson;
};

export type CallsGetResponse = CallsGetResponses[keyof CallsGetResponses];

export type CallsAnswerData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}/answer';
};

export type CallsAnswerErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsAnswerError = CallsAnswerErrors[keyof CallsAnswerErrors];

export type CallsAnswerResponses = {
    /**
     * OK
     */
    200: CallJson;
};

export type CallsAnswerResponse = CallsAnswerResponses[keyof CallsAnswerResponses];

export type CallsDtmfData = {
    body: CallsDtmfInputBodyWritable;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}/dtmf';
};

export type CallsDtmfErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsDtmfError = CallsDtmfErrors[keyof CallsDtmfErrors];

export type CallsDtmfResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CallsDtmfResponse = CallsDtmfResponses[keyof CallsDtmfResponses];

export type CallsHangupData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}/hangup';
};

export type CallsHangupErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsHangupError = CallsHangupErrors[keyof CallsHangupErrors];

export type CallsHangupResponses = {
    /**
     * OK
     */
    200: CallJson;
};

export type CallsHangupResponse = CallsHangupResponses[keyof CallsHangupResponses];

export type CallsHoldData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}/hold';
};

export type CallsHoldErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsHoldError = CallsHoldErrors[keyof CallsHoldErrors];

export type CallsHoldResponses = {
    /**
     * OK
     */
    200: CallJson;
};

export type CallsHoldResponse = CallsHoldResponses[keyof CallsHoldResponses];

export type CallsMergeData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}/merge';
};

export type CallsMergeErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsMergeError = CallsMergeErrors[keyof CallsMergeErrors];

export type CallsMergeResponses = {
    /**
     * OK
     */
    200: CallJson;
};

export type CallsMergeResponse = CallsMergeResponses[keyof CallsMergeResponses];

export type CallsRejectData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}/reject';
};

export type CallsRejectErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsRejectError = CallsRejectErrors[keyof CallsRejectErrors];

export type CallsRejectResponses = {
    /**
     * OK
     */
    200: CallJson;
};

export type CallsRejectResponse = CallsRejectResponses[keyof CallsRejectResponses];

export type CallsResumeData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/calls/{id}/resume';
};

export type CallsResumeErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type CallsResumeError = CallsResumeErrors[keyof CallsResumeErrors];

export type CallsResumeResponses = {
    /**
     * OK
     */
    200: CallJson;
};

export type CallsResumeResponse = CallsResumeResponses[keyof CallsResumeResponses];

export type EventsListData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: {
        /**
         * Numeric event ID; return events strictly newer
         */
        since?: number;
        /**
         * Filter by event kind (e.g. sms.arrived)
         */
        kind?: string;
        limit?: number;
    };
    url: '/v1/events';
};

export type EventsListErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type EventsListError = EventsListErrors[keyof EventsListErrors];

export type EventsListResponses = {
    /**
     * OK
     */
    200: EventsListOutputBody;
};

export type EventsListResponse = EventsListResponses[keyof EventsListResponses];

export type SmsListData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: {
        /**
         * Default: in
         */
        direction?: 'in' | 'out';
        /**
         * ULID; return items strictly newer
         */
        since?: string;
        /**
         * Max items
         */
        limit?: number;
    };
    url: '/v1/sms';
};

export type SmsListErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type SmsListError = SmsListErrors[keyof SmsListErrors];

export type SmsListResponses = {
    /**
     * OK
     */
    200: SmsListBody;
};

export type SmsListResponse = SmsListResponses[keyof SmsListResponses];

export type SmsSendData = {
    body: SmsSendInputBodyWritable;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
        /**
         * Replay-protection key (24h cache)
         */
        'Idempotency-Key'?: string;
    };
    path?: never;
    query?: {
        /**
         * If 1, accept any non-E.164 destination (e.g. short codes)
         */
        raw?: boolean;
    };
    url: '/v1/sms';
};

export type SmsSendErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type SmsSendError = SmsSendErrors[keyof SmsSendErrors];

export type SmsSendResponses = {
    /**
     * Accepted
     */
    202: OutboundSmsResponse;
};

export type SmsSendResponse = SmsSendResponses[keyof SmsSendResponses];

export type SmsDeleteData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sms/{id}';
};

export type SmsDeleteErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type SmsDeleteError = SmsDeleteErrors[keyof SmsDeleteErrors];

export type SmsDeleteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SmsDeleteResponse = SmsDeleteResponses[keyof SmsDeleteResponses];

export type SmsGetData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/sms/{id}';
};

export type SmsGetErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type SmsGetError = SmsGetErrors[keyof SmsGetErrors];

export type SmsGetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StatusGetData = {
    body?: never;
    headers: {
        /**
         * Bearer token
         */
        Authorization: string;
    };
    path?: never;
    query?: {
        /**
         * Force on-demand AT poll instead of cached values
         */
        refresh?: boolean;
    };
    url: '/v1/status';
};

export type StatusGetErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type StatusGetError = StatusGetErrors[keyof StatusGetErrors];

export type StatusGetResponses = {
    /**
     * OK
     */
    200: StatusResponseBody;
};

export type StatusGetResponse = StatusGetResponses[keyof StatusGetResponses];

export type VoicemailsListData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: {
        /**
         * Return only unheard voicemail
         */
        unread?: boolean;
        /**
         * Maximum items
         */
        limit?: number;
    };
    url: '/v1/voicemails';
};

export type VoicemailsListErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type VoicemailsListError = VoicemailsListErrors[keyof VoicemailsListErrors];

export type VoicemailsListResponses = {
    /**
     * OK
     */
    200: VoicemailListOutputBody;
};

export type VoicemailsListResponse = VoicemailsListResponses[keyof VoicemailsListResponses];

export type VoicemailsSyncData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/v1/voicemails/sync';
};

export type VoicemailsSyncErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type VoicemailsSyncError = VoicemailsSyncErrors[keyof VoicemailsSyncErrors];

export type VoicemailsSyncResponses = {
    /**
     * OK
     */
    200: SyncResult;
};

export type VoicemailsSyncResponse = VoicemailsSyncResponses[keyof VoicemailsSyncResponses];

export type VoicemailsDeleteData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/voicemails/{id}';
};

export type VoicemailsDeleteErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type VoicemailsDeleteError = VoicemailsDeleteErrors[keyof VoicemailsDeleteErrors];

export type VoicemailsDeleteResponses = {
    /**
     * No Content
     */
    204: void;
};

export type VoicemailsDeleteResponse = VoicemailsDeleteResponses[keyof VoicemailsDeleteResponses];

export type VoicemailsGetData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/voicemails/{id}';
};

export type VoicemailsGetErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type VoicemailsGetError = VoicemailsGetErrors[keyof VoicemailsGetErrors];

export type VoicemailsGetResponses = {
    /**
     * OK
     */
    200: VoicemailResponse;
};

export type VoicemailsGetResponse = VoicemailsGetResponses[keyof VoicemailsGetResponses];

export type VoicemailsUpdateData = {
    body: VoicemailUpdateInputBodyWritable;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/voicemails/{id}';
};

export type VoicemailsUpdateErrors = {
    /**
     * Error
     */
    default: ApiError;
};

export type VoicemailsUpdateError = VoicemailsUpdateErrors[keyof VoicemailsUpdateErrors];

export type VoicemailsUpdateResponses = {
    /**
     * OK
     */
    200: VoicemailResponse;
};

export type VoicemailsUpdateResponse = VoicemailsUpdateResponses[keyof VoicemailsUpdateResponses];

export type VoicemailsAudioData = {
    body?: never;
    headers: {
        Authorization: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/voicemails/{id}/audio';
};

export type VoicemailsAudioResponses = {
    /**
     * Voicemail audio with byte-range support
     */
    200: Blob | File;
};

export type VoicemailsAudioResponse = VoicemailsAudioResponses[keyof VoicemailsAudioResponses];
